import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Single Product",
  description: "Generated by create next app",
};

const SingleProductPage = () => {
  return <div>SingleProductPage</div>;
};

export default SingleProductPage;
