import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChildrenType } from "@/types";
import "./styles/index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: ChildrenType) => {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-main`}>{children}</body>
    </html>
  );
};

export default RootLayout;
