import { UserType } from "@/types";
import { Metadata } from "next";
import Pagination from "@/components/Pagination";
import getAllUser from "@/db/crud/getAllUser";
import Search from "@/components/Search";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = {
  title: "User Page",
  description: "Generated by create next app",
};

// it is a server component,
// we can't use any kind of useHook here...

type UsersPagePropsType = {
  searchParams: {
    [key: string]: string;
  };
};

const UsersPage = async ({ searchParams }: UsersPagePropsType) => {
  const query = searchParams?.q ?? "";

  const users = await getAllUser(query);

  return (
    <div className="">
      <div className="flex items-center justify-between my-4">
        <Search />

        <Link href="/dashboard/users/add">
          <button className="px-4 py-2 bg-green-600 rounded text-gray-800 font-semibold duration-150 hover:bg-emerald-500 hover:text-gray-700">
            Add New User
          </button>
        </Link>
      </div>

      <table className="w-full bg-sidebar rounded table-auto">
        <thead>
          <tr className="pt-4 px-4 rounded">
            <td className="p-4 bg-gray-800 rounded-tl">Name</td>
            <td className="p-4 bg-gray-800">Email</td>
            <td className="p-4 bg-gray-800">Created At</td>
            <td className="p-4 bg-gray-800">Role</td>
            <td className="p-4 bg-gray-800">Status</td>
            <td className="p-4 bg-gray-800 rounded-tr">Action</td>
          </tr>
        </thead>

        <tbody>
          {users.map((user: UserType) => {
            const status = user.isActive ? "Active" : "Pending";
            const userRole = user.isAdmin ? "Admin" : "User";
            const statusBg = user.isActive ? "bg-green-400" : "bg-gray-400";
            const userCreatedTime = user.createdAt?.toString().slice(4, 16);

            return (
              <tr key={user._id}>
                <td className="p-4">
                  <div className="flex items-center gap-2">
                    <Image
                      width={40}
                      height={40}
                      src={user.img}
                      alt={user.userName}
                      className="rounded-full"
                    />
                    {user.userName}
                  </div>
                </td>

                <td className="p-4">{user.email}</td>
                <td className="p-4">{userCreatedTime}</td>
                <td className="p-4">
                  <span className="">{userRole}</span>
                </td>

                <td className="p-4">
                  <span className={`p-1 rounded text-black ${statusBg}`}>
                    {status}
                  </span>
                </td>

                <td className="p-4">
                  <div className="flex items-center gap-2">
                    <Link
                      href={`/dashboard/users/${user._id}`}
                      className="bg-blue-500 px-2 py-1 rounded"
                    >
                      View
                    </Link>

                    <form action={""}>
                      <input type="hidden" name="id" value={"user._id"} />
                      <button className="bg-red-500 px-2 py-1 rounded">
                        Delete
                      </button>
                    </form>
                  </div>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>

      <Pagination />
    </div>
  );
};

export default UsersPage;
